development:
  cartodb_table: 'gid_development'
  cartodb_oauth_key: '9eXe381epWZKHqFcYaeeH3qvefI5JG2b5TYdzE0o'
  background_machine: 'ec2-107-22-142-254.compute-1.amazonaws.com'
  admin_user_edits_limit: 500

staging:
  cartodb_table: 'gid_staging'
  cartodb_oauth_key: '9eXe381epWZKHqFcYaeeH3qvefI5JG2b5TYdzE0o'
  background_machine: 'ec2-107-22-142-254.compute-1.amazonaws.com'
  admin_user_edits_limit: 500

test:
  cartodb_table: 'gid_test'
  cartodb_oauth_key: '9eXe381epWZKHqFcYaeeH3qvefI5JG2b5TYdzE0o'
  background_machine: 'ec2-107-22-142-254.compute-1.amazonaws.com'
  admin_user_edits_limit: 500

production:
  cartodb_table: 'gid_production_1'
  cartodb_oauth_key: '9eXe381epWZKHqFcYaeeH3qvefI5JG2b5TYdzE0o'
  background_machine: 'ec2-107-22-142-254.compute-1.amazonaws.com'
  admin_user_edits_limit: 500
