default: &default
  cartodb_oauth_key: '9eXe381epWZKHqFcYaeeH3qvefI5JG2b5TYdzE0o'
  background_machine: 'ec2-107-22-142-254.compute-1.amazonaws.com'
  admin_user_edits_limit: 500
  redis_url: <%= ENV["REDIS_URL"] %>

development:
  <<: *default
  cartodb_table: 'gid_production_1'

staging:
  <<: *default
  cartodb_table: 'gid_staging'

test:
  <<: *default
  cartodb_table: 'gid_test'

production:
  <<: *default
  cartodb_table: 'gid_production_1'
