default: &default
  admins:
    -
      login: <%= ENV.fetch('ADMIN_LOGIN') %>
      password: <%= ENV.fetch('ADMIN_PASSWORD') %>

development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
